### ISSUE TITLE
Metadata Core Profile - request from TT-GISC

### ISSUE THREAD

**Issue by hermannasensio** [wmo-im/wmcp-docs#7]
Request from GISCs list of proposed changes for WMO core metadata profle, e.g. missing nodes or description of services

**Comment by hermannasensio** [comment]
one task from TT-GISC meeting 2019:
-  there are two ways to represent WMO data policy, ie 1. to use gmx:Anchor and 2. free text:CharacterString Request is "to consider this example and to avoid in the next version of WMO Core Profile multiple encoding styles for crucial information to minimize the implementation work for the GISCs"

**Comment by hermannasensio** [comment]
note another action, a KPI checking for the Distribution key word [GlobalExchange|RegionalExchange|OriginatingCentre] can help TT-GICD:
form the TT-GISC meeting 2019: "(3) All Metadata has to be migrated to WMO Core Profile 1.3. GISC Toulouse can offer assistance on this. Each GISC has to make sure, that all Metadata contains the Distribution Key Word of GlobalExchange, RegionalExchange or OriginatingCentre. 
(4) Address the following issues (in order of priority)
   (a) Synchronization Status
   (b) Metadata Quality
   (c) Metadata Granularity
(5) TT-GISC implements procedures to monitor and follow-up issues on the Core Cache Completeness 
(6) Establish new Work Package 9"

**Comment by efucile** [comment]
1. Find a list of mandatory elements
2. Find a list of elements that need to have a constrained vocabulary. Use of the codes registry.
3. distributionScope must be valued and it is connected with caching global data.

**Comment by hermannasensio** [comment]
continue on https://github.com/wmo-im/wcmp
